In [1]:
import numpy as np

In [2]:
np.array(["asaa",5,4])

array(['asaa', '5', '4'], dtype='<U4')

In [3]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [4]:
type(np.array([1,2,3.0]))#ndarray means ndimensional array

numpy.ndarray

In [5]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [6]:
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [7]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [9]:
x[0][0]

1

In [10]:
x[0][1]

2

In [11]:
x[1][0]

3

In [12]:
x[1][1]

4

In [13]:
type(x[1][1])

numpy.int64

In [14]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [15]:
np.mat(np.array([[1,2],[3,4]]))

matrix([[1, 2],
        [3, 4]])

In [16]:
np.mat("1,2; 3,4")

matrix([[1, 2],
        [3, 4]])

In [17]:
a=[1,2]
np.array(a)

array([1, 2])

In [18]:
np.asarray(a)

array([1, 2])

In [19]:
issubclass(np.matrix,np.ndarray)

True

In [20]:
issubclass(np.ndarray,np.matrix)

False

# asanyarray

In [22]:
a=[1,2]
np.asanyarray(a)

array([1, 2])

In [24]:
a=np.mat([1,2])
a

matrix([[1, 2]])

In [25]:
np.asanyarray(a)#here as a is already in any form of array,asanyarray doesnot change its earlier format

matrix([[1, 2]])

In [27]:
np.array(a)#array simply convert to to array though we pass any form of array in it

array([[1, 2]])

# shallow copy

In [28]:
a=[1,2]
x=np.array(a)

In [29]:
x

array([1, 2])

In [30]:
y=x

In [31]:
y[0]

1

In [32]:
y[0]=10

In [33]:
y

array([10,  2])

In [34]:
x

array([10,  2])

# deep copy

In [35]:
a

[1, 2]

In [39]:
x=np.array(a)

In [40]:
y=np.copy(x)

In [41]:
y[0]

1

In [43]:
y[0]=50

In [44]:
y

array([50,  2])

In [45]:
x#here value of x doesnt change.hence the concept is known as deep copy

array([1, 2])